### ISSUE TITLE
All 'flutter:xxx' execute commands are failing if 'element' argument in it

### ISSUE THREAD

**Issue by RodaxQA** [igortavtib/robotframework-appiumflutterlibrary#11]
Appium v1.22.2
Flutter 2.8.1
Dart 2.15.1
robotframework 4.1.2
robotframework-appiumflutterlibrary 1.0.0b2

Keywords like :

1. wait_for_element --> `application.execute_script('flutter:waitFor', element)`
2. wait_for_element_absent -->  `application.execute_script('flutter:waitForAbsent', element)`
3. get_element_text --> `application.execute_script('flutter:getText', element)` (also see #9)
4. scroll_to_element --> `application.execute_script('flutter:scrollIntoView', element, 0)`

Are failing with similar Appium log `Error: input is invalid` : 
```
[HTTP] --> POST /wd/hub/session/e556a14a-d2af-4996-abfb-dbd3e3ce148c/execute/sync
[HTTP] {"script":"flutter:waitFor","args":[{"element-6066-11e4-a52e-4f735466cecf":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoid3JvbmdLZXkiLCJrZXlWYWx1ZVR5cGUiOiJTdHJpbmcifQ=="},20]}
[debug] [W3C (e556a14a)] Calling AppiumDriver.execute() with args: ["flutter:waitFor",[{"element-6066-11e4-a52e-4f735466cecf":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoid3JvbmdLZXkiLCJrZXlWYWx1ZVR5cGUiOiJTdHJpbmcifQ=="},20],"e556a14a-d2af-4996-abfb-dbd3e3ce148c"]
[debug] [FlutterDriver] Executing Flutter driver command 'execute'
[debug] [W3C (e556a14a)] Encountered internal error running command: Error: input is invalid {"element-6066-11e4-a52e-4f735466cecf":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoid3JvbmdLZXkiLCJrZXlWYWx1ZVR5cGUiOiJTdHJpbmcifQ=="}
[debug] [W3C (e556a14a)]     at Object.exports.decode (C:\Users\ggpf9966\AppData\Roaming\nvm\v12.16.1\node_modules\appium\node_modules\finder\nodejs\lib\base64url.ts:15:11)
[debug] [W3C (e556a14a)]     at Object.exports.deserialize (C:\Users\ggpf9966\AppData\Roaming\nvm\v12.16.1\node_modules\appium\node_modules\finder\nodejs\lib\deserializer.ts:4:14)
[debug] [W3C (e556a14a)]     at FlutterDriver.exports.executeElementCommand (C:\Users\ggpf9966\AppData\Roaming\nvm\v12.16.1\node_modules\appium\node_modules\appium-flutter-driver\lib\sessions\observatory.ts:128:41)
[debug] [W3C (e556a14a)]     at Object.waitFor (C:\Users\ggpf9966\AppData\Roaming\nvm\v12.16.1\node_modules\appium\node_modules\appium-flutter-driver\lib\commands\execute\wait.ts:20:14)
[debug] [W3C (e556a14a)]     at FlutterDriver.exports.execute (C:\Users\ggpf9966\AppData\Roaming\nvm\v12.16.1\node_modules\appium\node_modules\appium-flutter-driver\lib\commands\execute.ts:44:14)
[debug] [W3C (e556a14a)]     at commandExecutor (C:\Users\ggpf9966\AppData\Roaming\nvm\v12.16.1\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:335:9)
[debug] [W3C (e556a14a)]     at C:\Users\ggpf9966\AppData\Roaming\nvm\v12.16.1\node_modules\appium\node_modules\async-lock\lib\index.js:146:12
[debug] [W3C (e556a14a)]     at AsyncLock._promiseTry (C:\Users\ggpf9966\AppData\Roaming\nvm\v12.16.1\node_modules\appium\node_modules\async-lock\lib\index.js:280:31)
[debug] [W3C (e556a14a)]     at exec (C:\Users\ggpf9966\AppData\Roaming\nvm\v12.16.1\node_modules\appium\node_modules\async-lock\lib\index.js:145:9)
[debug] [W3C (e556a14a)]     at AsyncLock.acquire (C:\Users\ggpf9966\AppData\Roaming\nvm\v12.16.1\node_modules\appium\node_modules\async-lock\lib\index.js:162:3)
[debug] [W3C (e556a14a)]     at FlutterDriver.executeCommand (C:\Users\ggpf9966\AppData\Roaming\nvm\v12.16.1\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:348:39)
[debug] [W3C (e556a14a)]     at FlutterDriver.executeCommand (C:\Users\ggpf9966\AppData\Roaming\nvm\v12.16.1\node_modules\appium\node_modules\appium-flutter-driver\lib\driver.ts:132:22)
[debug] [W3C (e556a14a)]     at AppiumDriver.executeCommand (C:\Users\ggpf9966\AppData\Roaming\nvm\v12.16.1\node_modules\appium\lib\appium.js:563:36)
[debug] [W3C (e556a14a)]     at runMicrotasks (<anonymous>)
[debug] [W3C (e556a14a)]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[debug] [W3C (e556a14a)]     at asyncHandler (C:\Users\ggpf9966\AppData\Roaming\nvm\v12.16.1\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:297:21)
[HTTP] <-- POST /wd/hub/session/e556a14a-d2af-4996-abfb-dbd3e3ce148c/execute/sync 500 28 ms - 929
```

I think the root cause is because :

1. commands like "click" need a FlutterElement (https://github.com/appium-userland/appium-flutter-driver/blob/329a05120c016b32c58a2dc88747873df5248b46/example/python/example.py#L29) like `{"element-6066-11e4-a52e-4f735466cecf":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoid3JvbmdLZXkiLCJrZXlWYWx1ZVR5cGUiOiJTdHJpbmcifQ=="}`
2. but commands like "flutter:" only need the base64 value returned by `finder.by_xxx` (https://github.com/appium-userland/appium-flutter-driver/blob/329a05120c016b32c58a2dc88747873df5248b46/example/python/example.py#L32)

We can solve this (I tested it) by adding `element.id` instead of `element` everywhere there is a "flutter:" execute command
Like this : `application.execute_script('flutter:waitFor', element.id)`
The id is an internal base64 ID used by selenium (selenium\webdriver\remote\webelement.py)
Example id : `eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlU3RyaW5nIjoid3JvbmdLZXkiLCJrZXlWYWx1ZVR5cGUiOiJTdHJpbmcifQ==`

**Comment by igortavtib** [comment]
Hey, thanks for your contribution!

I'll test the solution you said and update the previous commands.

**Comment by marcosmko** [comment]
Hello all!

Thanks for this library!
Are you planning a new release with this fix soon? 🙏

**Comment by igortavtib** [comment]
I am working on this fix. I belive will be released soon!

**Comment by igortavtib** [comment]
This fix is at master. Will be realeased at beta.3!

**Comment by zastress** [comment]
Hello. Any news on the beta3?

**Comment by igortavtib** [comment]
Version 1.0.0 released with this fix.

I'm closing this issue.
