### ISSUE TITLE
Appium 2.0 Press KeyCode event doesn't work

### ISSUE THREAD

**Issue by yahyakara** [igortavtib/robotframework-appiumflutterlibrary#22]
When I use the Press KeyCode event, the driver trow following error on Appium 2.0. 

WebDriverException: Message: Method has not yet been implemented
Stacktrace:
NotYetImplementedError: Method has not yet been implemented
    at FlutterDriver.executeCommand (/Users/yahya.kara/.appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:67:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at FlutterDriver.executeCommand (/Users/yahya.kara/.appium/node_modules/appium-flutter-driver/lib/driver.ts:139:16)
    at defaultBehavior (/usr/local/lib/node_modules/appium/lib/appium.js:673:14)
    at AppiumDriver.executeWrappedCommand (/usr/local/lib/node_modules/appium/lib/appium.js:763:16)
    at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:685:17)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:346:19)
    
Could you help me  about  How can I use the press key code keyword

**Comment by igortavtib** [comment]
Hey @yahyakara

This error is occurring cause this method was not implemented yet.

 We are working in the new version with this method implemented.
